#!/bin/bash

DIRNAME=`dirname "$0"`
if [ "$DIRNAME" = "." ]; then
  DIRNAME="$PWD"
fi

DATADIR="$DIRNAME"
CONFDIR="$DIRNAME"

if [ "$JAVA" = "" ]; then
  JAVA=`which java`
  if [ "$JAVA" = "" ]; then
    if [ "$JAVA_HOME" = "" ]; then
      echo 'Unable to start a JVM : $JAVA is not set and java is not in PATH and $JAVA_HOME is not set'
      exit
    fi
    JAVA="$JAVA_HOME/bin/java"
  fi
fi

if [ "$JAVA_OPTS" = "" ]; then
  JAVA_OPTS=-Djava.net.useSystemProxies=true
fi

DEMO2_OPTS=($JAVA_OPTS)
DEMO2_ARGS=()

if "$JAVA" --add-modules java.base -version >/dev/null 2>&1; then
  DEMO2_OPTS=("${DEMO2_OPTS[@]}" --add-modules ALL-DEFAULT)
  DEMO2_ARGS=(-p "$DATADIR/lib/vestige.core-${vestige.core.version}.jar" -m fr.gaellalire.vestige.core frmp "$DATADIR" "$DATADIR/unix-classpath.txt" fr.gaellalire.vestige_app.demo2.mod1/fr.gaellalire.vestige_app.demo2.mod1.Mod1)
else
  DEMO2_ARGS=(-jar "$DATADIR/lib/vestige.core-${vestige.core.version}.jar" --before 'javax/xml/bind/.*' frcp "$DATADIR" "$DATADIR/unix-classpath.txt" fr.gaellalire.vestige_app.demo2.mod1.Mod1)
fi

exec "$JAVA" "${DEMO2_OPTS[@]}" "${DEMO2_ARGS[@]}"
